export * from './GVKData';
export * from './integrity-data';
export * from './informa-data';
export * from './ontology-data';
//UNCOMMENT TO ENABLE ADIS--> export * from './adis-data';
export * from './assay-data';
export * from './vendor-data';
export * from './wiki-data';
export * from './primary-screen-data';
export * from './psd-details';
